PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?top_level_id ?top_level_label (COUNT(DISTINCT ?cls) AS ?count)
WHERE {
  # EVS asserted IRIs and OBO edition IRIs (disorders mirror uses the latter).
  VALUES ?top_level_id {
    <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C7057>
    <http://purl.obolibrary.org/obo/NCIT_C7057>
    <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C2991>
    <http://purl.obolibrary.org/obo/NCIT_C2991>
    <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C3262>
    <http://purl.obolibrary.org/obo/NCIT_C3262>
  }
  ?top_level_id rdfs:label ?top_level_label .
  ?cls a owl:Class ;
       rdfs:subClassOf+ ?top_level_id .
}
GROUP BY ?top_level_id ?top_level_label
